### ISSUE TITLE
Dark White and Dark Black

### ISSUE THREAD

**Issue by ConductiveInsulation** [Fraser999/Colour#1]
The Example on Crates.io and here contains `dark_white!("dark_white ");` and `dark_black!("dark_black ");` both colours arent in the script because Dark White would be grey and black is already dark, maybe remove them from the example since it wouldnt really make a point to create them. 

I'd also suggest renaming the function `all_colours()` to `main()`, that way the example could be copied and would run without further editing which is always a nice thing for examples.

**Comment by Fraser999** [comment]
Thanks for the report (and apologies for the delay in responding!)

Both points should be fixed in commit [4259e27](https://github.com/Fraser999/Colour/commit/4259e279a120907384d237836b8642cb63211b8a).
